# Assignment Day 10

# Question 1:

Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np
array1=np.array([10,20,30,40,50])
array2=np.array([15,20,25,40,45])



In [10]:
np.greater(array1,array2)

array([False, False,  True, False,  True])

In [7]:
np.greater_equal(array1,array2)

array([False,  True,  True,  True,  True])

In [8]:
np.less(array1,array2)

array([ True, False, False, False, False])

In [9]:
np.less_equal(array1,array2)

array([ True,  True, False,  True, False])

# Question 2:

Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [13]:
zero=np.zeros(10)

In [14]:
ones=np.ones(10)


In [15]:
fives=np.ones(10)*5

In [16]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Question 3:

Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [20]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.sum(array)

45

In [24]:
array.sum(axis=0)

array([12, 15, 18])

In [27]:
array.sum(axis=1)

array([ 6, 15, 24])

# Question 4:

Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [30]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
array2=np.array([[7,8,9],[4,5,6],[1,2,3]])


In [33]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
array2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [32]:
array1+array2

array([[ 8, 10, 12],
       [ 8, 10, 12],
       [ 8, 10, 12]])

In [35]:
array1-array2

array([[-6, -6, -6],
       [ 0,  0,  0],
       [ 6,  6,  6]])

In [36]:
array1*array2

array([[ 7, 16, 27],
       [16, 25, 36],
       [ 7, 16, 27]])

In [37]:
array1/array2

array([[0.14285714, 0.25      , 0.33333333],
       [1.        , 1.        , 1.        ],
       [7.        , 4.        , 3.        ]])

# Question 5:

Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [48]:
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0, 30, 45, 60, 90)) * np.pi / 180))
print("\ncosine: array of angles given in degrees")
print(np.cos(np.array((0, 30, 45, 60, 90)) * np.pi / 180))
print("\ntangent: array of angles given in degrees")
print(np.tan(np.array((0, 30, 45, 60, 90)) * np.pi / 180))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]

cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Question 6:

Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [58]:
import pandas as pd

In [59]:
dic={'Name':['xx','yy','zz'],'Age':[10,20,30],'Sex':['m','f','m']}

In [70]:
df=pd.DataFrame(dic)

In [71]:
df.index=[1,2,3]

In [72]:
df

Name  Age Sex
1   xx   10   m
2   yy   20   f
3   zz   30   m

In [67]:
d={'one':pd.Series([100,200,300],index=[1,2,3]),
   'two':pd.Series([400,500,600],index=[1,3,5])}


In [68]:
pd.DataFrame(d)

one    two
1  100.0  400.0
2  200.0    NaN
3  300.0  500.0
5    NaN  600.0

# Question 7:

Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [78]:
dic={'Name':['xx','yy','zz'],'Age':[15,17,19],'Sex':['m','f','m'],'score':[50,45,48]}

In [86]:
df=pd.DataFrame(dic)

In [87]:
df[['Name','score']]

Name  score
0   xx     50
1   yy     45
2   zz     48

# Question 8:

Write a Pandas program to join the two given dataframes along rows and assign all data.

In [88]:
import os

In [89]:
os.chdir("F:")

In [90]:
marks1=pd.read_excel('marks1.xlsx')

In [91]:
marks2=pd.read_excel('marks2.xlsx')

In [97]:
marks1.head(10)

ID designation  rating
0   1   Associate     5.0
1   2          PA     4.0
2   3          SA     5.0
3   4     Manager     4.0
4   5   Associate     3.5
5   6          PA     5.0
6   7          SA     4.0
7   8     Manager     3.5

In [98]:
marks2.head(10)

ID    name  salary
0   1  vishnu  100000
1   2    arun   50000
2   3   ajith   75000
3   4   vijay   80000
4   5   surya   60000
5   6  vikram   75000
6   7    anil   40000

In [103]:
join=marks1.merge(marks2,how='outer',on='ID')

In [104]:
join

ID designation  rating    name    salary
0   1   Associate     5.0  vishnu  100000.0
1   2          PA     4.0    arun   50000.0
2   3          SA     5.0   ajith   75000.0
3   4     Manager     4.0   vijay   80000.0
4   5   Associate     3.5   surya   60000.0
5   6          PA     5.0  vikram   75000.0
6   7          SA     4.0    anil   40000.0
7   8     Manager     3.5     NaN       NaN

# Question 9:

Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [106]:
join.isnull()

ID  designation  rating   name  salary
0  False        False   False  False   False
1  False        False   False  False   False
2  False        False   False  False   False
3  False        False   False  False   False
4  False        False   False  False   False
5  False        False   False  False   False
6  False        False   False  False   False
7  False        False   False   True    True

# Question 10:

Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [111]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [112]:
s

a    10
b    20
c    30
dtype: int64